python sheets_auto_fill.py --log=log/test_english_kimi.log --row=2 --col=F
python sheets_auto_fill.py --log=log/test_english_doubao.log --row=3 --col=F
python sheets_auto_fill.py --log=log/test_english_qwen.log --row=4 --col=F
python sheets_auto_fill.py --log=log/test_english_qwen2.5.log --row=5 --col=F
python sheets_auto_fill.py --log=log/test_arabic_kimi.log --row=2 --col=I
python sheets_auto_fill.py --log=log/test_arabic_doubao.log --row=3 --col=I
python sheets_auto_fill.py --log=log/test_arabic_qwen.log --row=4 --col=I
python sheets_auto_fill.py --log=log/test_arabic_qwen2.5.log --row=5 --col=I
python sheets_auto_fill.py --log=log/test_japanese_kimi.log --row=2 --col=L
python sheets_auto_fill.py --log=log/test_japanese_doubao.log --row=3 --col=L
python sheets_auto_fill.py --log=log/test_japanese_qwen.log --row=4 --col=L
python sheets_auto_fill.py --log=log/test_japanese_qwen2.5.log --row=5 --col=L
python sheets_auto_fill.py --log=log/test_french_kimi.log --row=2 --col=O
python sheets_auto_fill.py --log=log/test_french_doubao.log --row=3 --col=O
python sheets_auto_fill.py --log=log/test_french_qwen.log --row=4 --col=O
python sheets_auto_fill.py --log=log/test_french_qwen2.5.log --row=5 --col=O
python sheets_auto_fill.py --log=log/test_russian_kimi.log --row=2 --col=R
python sheets_auto_fill.py --log=log/test_russian_doubao.log --row=3 --col=R
python sheets_auto_fill.py --log=log/test_russian_qwen.log --row=4 --col=R
python sheets_auto_fill.py --log=log/test_russian_qwen2.5.log --row=5 --col=R
python sheets_auto_fill.py --log=log/test_kimi_t0.0.log --row=2 --col=AK
python sheets_auto_fill.py --log=log/test_doubao_t0.0.log --row=3 --col=AK
python sheets_auto_fill.py --log=log/test_qwen_t0.0.log --row=4 --col=AK
python sheets_auto_fill.py --log=log/test_qwen25_t0.0.log --row=5 --col=AK
python sheets_auto_fill.py --log=log/test_kimi_t0.2.log --row=2 --col=AN
python sheets_auto_fill.py --log=log/test_doubao_t0.2.log --row=3 --col=AN
python sheets_auto_fill.py --log=log/test_qwen_t0.2.log --row=4 --col=AN
python sheets_auto_fill.py --log=log/test_qwen25_t0.2.log --row=5 --col=AN
python sheets_auto_fill.py --log=log/test_kimi_t0.5.log --row=2 --col=AQ
python sheets_auto_fill.py --log=log/test_doubao_t0.5.log --row=3 --col=AQ
python sheets_auto_fill.py --log=log/test_qwen_t0.5.log --row=4 --col=AQ
python sheets_auto_fill.py --log=log/test_qwen25_t0.5.log --row=5 --col=AQ
python sheets_auto_fill.py --log=log/test_kimi_t0.7.log --row=2 --col=AT
python sheets_auto_fill.py --log=log/test_doubao_t0.7.log --row=3 --col=AT
python sheets_auto_fill.py --log=log/test_qwen_t0.7.log --row=4 --col=AT
python sheets_auto_fill.py --log=log/test_qwen25_t0.7.log --row=5 --col=AT
python sheets_auto_fill.py --log=log/test_kimi_t1.0.log --row=2 --col=AW
python sheets_auto_fill.py --log=log/test_doubao_t1.0.log --row=3 --col=AW
python sheets_auto_fill.py --log=log/test_qwen_t1.0.log --row=4 --col=AW
python sheets_auto_fill.py --log=log/test_qwen25_t1.0.log --row=5 --col=AW
python sheets_auto_fill.py --log=log/test_kimi_t1.5.log --row=2 --col=AZ
python sheets_auto_fill.py --log=log/test_doubao_t1.5.log --row=3 --col=AZ
python sheets_auto_fill.py --log=log/test_qwen_t1.5.log --row=4 --col=AZ
python sheets_auto_fill.py --log=log/test_qwen25_t1.5.log --row=5 --col=AZ
python sheets_auto_fill.py --log=log/test_kimi_t2.0.log --row=2 --col=BC
python sheets_auto_fill.py --log=log/test_doubao_t2.0.log --row=3 --col=BC
python sheets_auto_fill.py --log=log/test_qwen_t2.0.log --row=4 --col=BC
python sheets_auto_fill.py --log=log/test_qwen25_t2.0.log --row=5 --col=BC